---
- hosts: localhost
  vars_files: ./vars.yaml

  tasks: 
  - name: Clone multiple esxi vms from Template
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item }}"
      state: "poweredoff"
      datacenter: '{{ datacenter_name }}'
      folder: "{{ folder_prefix + student_ID }}"
      esxi_hostname: '{{ esxi_hostname }}'
      datastore: "{{ datastore_name }}"
      template: "{{ esxi_template_name }}"
    loop:
      - "{{student_ID+'-SA-ESXi-01'}}"
      - "{{student_ID+'-SA-ESXi-02'}}"
      - "{{student_ID+'-SA-ESXi-03'}}"
    delegate_to: localhost


# https://stackoverflow.com/questions/59626587/how-to-change-vmware-network-adapter-with-ansible
  - name: Adding ESXi VMs Network Interfaces - Mgmt
    community.vmware.vmware_guest_network:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item[0] }}"
      label: "{{ item[1] }}"
      network_name: "{{ student_ID + '-SA-Mgmt' }}"
      state: present
      force: yes
    with_nested:
      - [ "{{student_ID+'-SA-ESXi-01'}}", "{{student_ID+'-SA-ESXi-02'}}", "{{student_ID+'-SA-ESXi-03'}}" ]
      - [ "Network adapter 1", "Network adapter 2" ]
    delegate_to: localhost

# https://stackoverflow.com/questions/59626587/how-to-change-vmware-network-adapter-with-ansible
  - name: Adding ESXi VMs Network Interfaces - Trunk
    community.vmware.vmware_guest_network:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item[0] }}"
      label: "{{ item[1] }}"
      network_name: "{{ student_ID + '-SA-Trunk' }}"
      state: present
      force: yes
    with_nested:
      - [ "{{student_ID+'-SA-ESXi-01'}}", "{{student_ID+'-SA-ESXi-02'}}", "{{student_ID+'-SA-ESXi-03'}}" ]
      - [ "Network adapter 3", "Network adapter 4" ]
    delegate_to: localhost



# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html
  - name: Power on ESXi VMs
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item }}"
      state: "poweredon"
    loop:
      - "{{student_ID+'-ESXi-01'}}"
      - "{{student_ID+'-ESXi-02'}}"
      - "{{student_ID+'-ESXi-03'}}"
    delegate_to: localhost
  
