---
- hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
    project_id: "PJT#5"
    vcenter_hostname: "192.168.3.100"
    vcenter_username: "administrator@vsphere.reca"
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    folder_prefix: "/Datacenter/vm/Project/"
    esxi_hostname: "192.168.3.103"
    esxi_password: "VMware1!"
    esxi_username: "root"
    public_net: "VM-192.168.3.x"
    private_net: "{{ project_id + '-Openshift' }}"
    datastore_name: "RECA-ESXi-03"

  tasks: 
    - name: Create a virtual machine on given ESXi hostname
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: 'false'
        datacenter: '{{datacenter_name}}'
        folder: '{{ folder_prefix + project_id }}'

        name: '{{ item.vmname }}'
        state: poweredoff
        guest_id: '{{ item.guest_id }}'
        esxi_hostname: "{{ esxi_hostname }}"
        hardware:
          num_cpus: '{{ item.cpus }}'
          memory_mb: '{{ item.memory }}'
          scsi: paravirtual
        disk:
        - size_gb: '{{ item.disk_gb }}'
          type: thin
          datastore: '{{ datastore_name }}'
        networks:
        - name: '{{ private_net }}'
          device_type: vmxnet3
        cdrom:
        - controller_number: 0
          unit_number: 0
          state: present
          type: iso
          iso_path: '{{ item.iso }}'
      with_items:
      - { vmname: "{{ project_id + '-Bastion'}}", guest_id: rhel8_64Guest, cpus: 4, memory: 16384, disk_gb: 120, iso: '[RECA-ESXi-03]\ISO\rhel-8.5-x86_64-dvd.iso' }
      - { vmname: "{{ project_id + '-Bootstrap'}}", guest_id: rhel8_64Guest, cpus: 4, memory: 16384, disk_gb: 120, iso: '[RECA-ESXi-03]\ISO\rhel-8.5-x86_64-dvd.iso' }
      - { vmname: "{{ project_id + '-Master-01'}}", guest_id: rhel8_64Guest, cpus: 4, memory: 16384, disk_gb: 120, iso: '[RECA-ESXi-03]\ISO\rhcos-412.86.202212081411-0-live.x86_64.iso' }
      - { vmname: "{{ project_id + '-Master-02'}}", guest_id: rhel8_64Guest, cpus: 4, memory: 16384, disk_gb: 120, iso: '[RECA-ESXi-03]\ISO\rhcos-412.86.202212081411-0-live.x86_64.iso' }
      - { vmname: "{{ project_id + '-Master-03'}}", guest_id: rhel8_64Guest, cpus: 4, memory: 16384, disk_gb: 120, iso: '[RECA-ESXi-03]\ISO\rhcos-412.86.202212081411-0-live.x86_64.iso' }
      - { vmname: "{{ project_id + '-Worker-01'}}", guest_id: rhel8_64Guest, cpus: 2, memory: 8192, disk_gb: 120, iso: '[RECA-ESXi-03]\ISO\rhcos-412.86.202212081411-0-live.x86_64.iso' }
      - { vmname: "{{ project_id + '-Worker-02'}}", guest_id: rhel8_64Guest, cpus: 2, memory: 8192, disk_gb: 120, iso: '[RECA-ESXi-03]\ISO\rhcos-412.86.202212081411-0-live.x86_64.iso' }
      - { vmname: "{{ project_id + '-Worker-03'}}", guest_id: rhel8_64Guest, cpus: 2, memory: 8192, disk_gb: 120, iso: '[RECA-ESXi-03]\ISO\rhcos-412.86.202212081411-0-live.x86_64.iso' }
      delegate_to: localhost
      register: deploy_vm

    - name: Change & Modify Bastion VM Network
      community.vmware.vmware_guest_network:
        hostname: "{{ vcenter_hostname }}"
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: 'false'
        name: "{{ project_id + '-Bastion'}}"
        network_name: '{{ item.network }}'
        lable: ''{ iem.lable }}'
        state: present
        connected: yes
      with_items:
      - { network: "{{ public_net }}", label: "Network Adapter 1" }
      - { network: "{{ private_net }}", label: "Network Adapter 2" }
      delegate_to: localhost

    - name: Add Bastion Disks
      community.vmware.vmware_guest_disk:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: 'false'
        datacenter: '{{datacenter_name}}'        
        name: "{{ project_id + '-Bastion'}}"
        disk:
        - size_mb: 200
          type: thin
          datastore: '{{ datastore_name }}'
          state: present
          scsi_controller: 1
          unit_number: 1
          scsi_type: 'paravirtual'
          disk_mode: 'persistent'
      delegate_to: localhost
      register: disk_facts
