# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_dvswitch_module.html
# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_dvs_portgroup_module.html

---
- hosts: localhost
  tasks:
    - name: Create dvSwitch
      community.vmware.vmware_dvswitch:
        hostname: '10.10.10.10'
        username: 'administrator@vsphere.local'
        password: 'VMware1!'
        validate_certs: no
        datacenter: 'KH'
        switch: dSwitch
        version: 7.0.3
        mtu: 1500
        uplink_quantity: 2
        discovery_protocol: cdp
        discovery_operation: listen
        state: present
      delegate_to: localhost

    - name: Waiting 10 seconds for completing switch
      wait_for:
        timeout: 10
      delegate_to: localhost

    - name: Add Host to dVS
      community.vmware.vmware_dvs_host:
        hostname: '10.10.10.10'
        username: 'administrator@vsphere.local'
        password: 'VMware1!'
        validate_certs: no
        esxi_hostname: 'sa-esxi-01.vclass.local'
        switch_name: dSwitch
        vmnics:
            - vmnic2
            - vmnic3
        state: present
      delegate_to: localhost
    
    - name: Add Host to dVS
      community.vmware.vmware_dvs_host:
        hostname: '10.10.10.10'
        username: 'administrator@vsphere.local'
        password: 'VMware1!'
        validate_certs: no
        esxi_hostname: 'sa-esxi-02.vclass.local'
        switch_name: dSwitch
        vmnics:
            - vmnic2
            - vmnic3
        state: present
      delegate_to: localhost

    - name: Add Host to dVS
      community.vmware.vmware_dvs_host:
        hostname: '10.10.10.10'
        username: 'administrator@vsphere.local'
        password: 'VMware1!'
        validate_certs: no
        esxi_hostname: 'sa-esxi-03.vclass.local'
        switch_name: dSwitch
        vmnics:
            - vmnic2
            - vmnic3
        state: present
      delegate_to: localhost

    - name: Adding vlan vsan portgroup
      community.vmware.vmware_dvs_portgroup:
        hostname: '10.10.10.10'
        username: 'administrator@vsphere.local'
        password: 'VMware1!'
        validate_certs: no
        portgroup_name: dpg_vsan
        switch_name: dSwitch
        vlan_id: 100
        num_ports: 8
        port_binding: static
        state: present
      delegate_to: localhost

    - name: Adding vlan iscsi portgroup
      community.vmware.vmware_dvs_portgroup:
        hostname: '10.10.10.10'
        username: 'administrator@vsphere.local'
        password: 'VMware1!'
        validate_certs: no
        portgroup_name: dpg_iscsi
        switch_name: dSwitch
        vlan_id: 11
        num_ports: 8
        port_binding: static
        state: present
      delegate_to: localhost

    - name: Adding vlan vmotion portgroup
      community.vmware.vmware_dvs_portgroup:
        hostname: '10.10.10.10'
        username: 'administrator@vsphere.local'
        password: 'VMware1!'
        validate_certs: no
        portgroup_name: dpg_vmotion
        switch_name: dSwitch
        vlan_id: 12
        num_ports: 8
        port_binding: static
        state: present
      delegate_to: localhost

    - name: Adding vlan prod portgroup
      community.vmware.vmware_dvs_portgroup:
        hostname: '10.10.10.10'
        username: 'administrator@vsphere.local'
        password: 'VMware1!'
        validate_certs: no
        portgroup_name: dpg_prod
        switch_name: dSwitch
        vlan_id: 13
        num_ports: 8
        port_binding: static
        state: present
      delegate_to: localhost

    - name: Create vlan portgroup with all security and port policies iscsi
      community.vmware.vmware_dvs_portgroup:
        hostname: '10.10.10.10'
        username: 'administrator@vsphere.local'
        password: 'VMware1!'
        validate_certs: no
        portgroup_name: dpg_iscsi
        switch_name: dSwitch
        vlan_id: 11
        num_ports: 8
        port_binding: static
        state: present
      delegate_to: localhost

    - name: Create vlan portgroup with all security and port policies vmotion
      community.vmware.vmware_dvs_portgroup:
        hostname: '10.10.10.10'
        username: 'administrator@vsphere.local'
        password: 'VMware1!'
        validate_certs: no
        portgroup_name: dpg_vmotion
        switch_name: dSwitch
        vlan_id: 12
        num_ports: 8
        port_binding: static
        state: present
      delegate_to: localhost

    - name: Create vlan portgroup with all security and port policies prod
      community.vmware.vmware_dvs_portgroup:
        hostname: '10.10.10.10'
        username: 'administrator@vsphere.local'
        password: 'VMware1!'
        validate_certs: no
        portgroup_name: dpg_prod
        switch_name: dSwitch
        vlan_id: 13
        num_ports: 8
        port_binding: static
        state: present
      delegate_to: localhost

    - name: Create vlan portgroup with all security and port policies vsan
      community.vmware.vmware_dvs_portgroup:
        hostname: '10.10.10.10'
        username: 'administrator@vsphere.local'
        password: 'VMware1!'
        validate_certs: no
        portgroup_name: dpg_vsan
        switch_name: dSwitch
        vlan_id: 100
        num_ports: 8
        port_binding: static
        state: present
      delegate_to: localhost
