apiVersion: apps/v1
kind: Deployment
metadata:
 name: deploy-ldapsrv
spec:
 replicas: 1
 selector:
   matchLabels:
     app: ldapsrv
 template:
   metadata:
     labels:
       app: ldapsrv
   spec:
     containers:
     - name: pod-ldapsrv
       image: ahneunji/ldap-server:2.0
       ports:
       - containerPort: 389
         protocol: TCP
       - containerPort: 636
         protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
 name: svc3-ldapsrv
spec:
 ports:
   - name: ldapsrv-port1
     port: 389
     targetPort: 389
     nodePort: 30389
     protocol: TCP
   - name: ldapsrv-port2
     port: 636
     targetPort: 636
     nodePort: 30636
     protocol: TCP
 selector:
   app: ldapsrv