apiVersion: apps/v1
kind: Deployment
metadata:
 name: deploy-websrv
spec:
 replicas: 3
 selector:
   matchLabels:
     app: websrv
 template:
   metadata:
     labels:
       app: websrv
   spec:
    containers:
    - name: pod-websrv
      image: ahneunji/web-server:3.0
      ports:
      - containerPort: 80
      volumeMounts:
      - name: nfs-html
        mountPath: /var/www/html
      - name: nfs-log
        mountPath: /var/log/nginx
    volumes:
    - name: nfs-html
      nfs:
       server: 20.20.50.50
       path: /html
    - name: nfs-log
      nfs:
       server: 20.20.50.50
       path: "/log"
---
apiVersion: v1
kind: Service
metadata:
 name: svc-websrv
spec:
 ports:
   - name: web-port
     port: 80
     targetPort: 80
     nodePort: 30000
     protocol: TCP
 selector:
   app: websrv
 type: NodePort