## https://doc.skill.or.kr/dockerfile-docker-image

# docker login
# docker build-t tomcat_mariadb:mariadb
# docker images
# docker run -d tomcat_mariadb:mariadb
# docker tag tomcat_mariadb:mariadb bchwang/tomcat_mariadb:mariadb
# docker push bchwang/tomcat_mariadb:mariadb  
# Docker Hub 에 개인 개정으로 로그인 후 Docker Image 및 Tag 확인

### 빌드할 버전    
version: '2'

### 서비스 설정    
services:
  mariadb:
    image: tomcat_mariadb:mariadb
    restart: always

  nginx-tomcat:
    image: tomcat_mariadb:nginx_tomcat
    restart: always
    ports:
      - 80:80
    links:
      - mariadb
