# https://doc.skill.or.kr/dockerfile-docker-image

# docker login
# docker build -t tomcat_mariadb:nginx_tomcat .
# docker images ## 로컬에 저장된 Docker Images 확인
# docker run –d –p 80:80 tomcat_mariadb: nginx_tomcat 
# docker tag tomcat_mariadb:nginx_tomcat bchwang/tomcat_mariadb:nginx_tomcat 
# docker push bchwang/tomcat_mariadb: nginx_tomcat 
# Docker Hub 에 개인 개정으로 로그인 후 Docker Image 및 Tag 확인

### 빌드할 버전    
version: '2'

### 서비스 설정    
services:
  mariadb:
    image: bchwang/tomcat_mariadb:mariadb
    restart: always

  nginx-tomcat:
    image: bchwang/tomcat_mariadb:nginx_tomcat
    restart: always
    ports:
      - 80:80
    links: # 서비스 연
      - mariadb
