apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    app: tomcat
  namespace: phx
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: tomcat
  type: ClusterIP
