## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_export_ovf_module.html#ansible-collections-community-vmware-vmware-export-ovf-module

---
- hosts: localhost
  vars_files: ./vars.yml

  tasks:
  - name : export_vm_ovf
    community.vmware.vmware_export_ovf:
      hostname: '{{ vcenter_hostname }}' 
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      name: "{{ student_ID + 'ESXi_Host' }}"
      export_dir: /mnt/c/test
      export_with_extraconfig: true
    delegate_to: localhost
