## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html

---
- hosts: localhost
  vars_files: ./vars.yml

  tasks: 
    - name: Create a virtual machine from Windows customize
      community.vmware.vmware_guest:
        hostname: '{{ my_vcenter_hostname }}'
        username: '{{ my_vcenter_username }}'
        password: '{{ my_vcenter_password }}'
        validate_certs: 'false'
        folder: "/"
        datacenter: TEST
        name: "k8s-master"
        state: poweredon
        guest_id: ubuntu64Guest
        esxi_hostname: "sa-esxi-04.vclass.local"   #"phx-esxi-01.vclass.local"
        disk:
        - size_gb: 16
          type: thick
          datastore: iSCSI-0
        hardware:
          memory_mb: 4096
          num_cpus: 2
        networks:
        - name: "dpg_prod"  # PHX-Mgmt 포트 그룹에 연결
          device_type: vmxnet3
        cdrom:
        - controller_number: 0
          unit_number: 0
          state: present
          type: iso
          iso_path: "[iSCSI-0] contentlib-8275da38-ceee-408c-ac73-2a44139ee60c/a3d842ce-446e-43c6-a17b-c488f6fdcdfc/ubuntu-20.04.4-desktop-amd64_5e4e474d-f282-4533-8d41-8e39496621b0.iso"
      delegate_to: localhost
      register: deploy