## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html

---
- hosts: localhost
  vars_files: ./vars.yml

  tasks: 
    - name: Create a virtual machine from Windows customize
      community.vmware.vmware_guest:
        hostname: '{{ my_vcenter_hostname }}'
        username: '{{ my_vcenter_username }}'
        password: '{{ my_vcenter_password }}'
        validate_certs: 'false'
        folder: "/"
        datacenter: TEST
        name: '{{ item.vmname }}'
        state: poweredon
        guest_id: ubuntu64Guest
        esxi_hostname: "sa-esxi-04.vclass.local"   #"phx-esxi-01.vclass.local"
        disk:
        - size_gb: 16
          type: thick
          datastore: test-iscsi
        hardware:
          memory_mb: 4096
          num_cpus: 2
        networks:
        - name: "dpg_prod"  # PHX-Mgmt 포트 그룹에 연결
          device_type: vmxnet3
        cdrom:
        - controller_number: 0
          unit_number: 0
          state: present
          type: iso
          iso_path: "[nfs] ubuntu-20.04.4-desktop-amd64.iso"
      with_items:
      - {vmname: "k8s-master", hostname: "sa-esxi-04.vclass.local" }
      - {vmname: "k8s-worker-01", hostname: "sa-esxi-05.vclass.local" }
      - {vmname: "k8s-worker-02", hostname: "sa-esxi-06.vclass.local" }  
      - {vmname: "k8s-worker-03", hostname: "sa-esxi-06.vclass.local" }  
      delegate_to: localhost
      register: deploy