## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_file_operation_module.html#ansible-collections-community-vmware-vmware-guest-file-operation-module 
## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vm_shell_module.html

---
- hosts: localhost
  vars_files: ./vars.yml

  tasks: 
    - name: Copy shell script to VM # 가상 머신에 shell script를 복사, task로 하나씩 등록하기
      community.vmware.vmware_guest_file_operation:
        hostname: '{{ my_vcenter_hostname }}'
        username: '{{ my_vcenter_username }}'
        password: '{{ my_vcenter_password }}'
        validate_certs: 'false'
        vm_id: "k8s-master" #가상머신을 이름으로 찾아감
        vm_id_type: vm_name
        vm_username: 'phoenix'
        vm_password: 'VMware1!'
        copy:
            src: "/mnt/c/test/Phoenix/eunji/set_k8s_master.sh"
            dest: "/home/phoenix/setting.sh"
            overwrite: true
      delegate_to: localhost

    - name: Execute shell script on ESXi host
      community.vmware.vmware_vm_shell:
        hostname: '{{ my_vcenter_hostname }}'
        username: '{{ my_vcenter_username }}'
        password: '{{ my_vcenter_password }}'
        validate_certs: 'false'
        vm_id: "k8s-master"
        vm_id_type: vm_name
        vm_username: 'phoenix'
        vm_password: 'VMware1!'
        vm_shell: /usr/bin/bash
        vm_shell_args: 
          "/home/phoenix/setting.sh"
        wait_for_process: True
        timeout: 120
      delegate_to: localhost

    - name: Delete copied shell script #실행한 shell script 삭제
      community.vmware.vmware_vm_shell:
        hostname: '{{ my_vcenter_hostname }}'
        username: '{{ my_vcenter_username }}'
        password: '{{ my_vcenter_password }}'
        validate_certs: 'false'
        vm_id: "k8s-master"
        vm_id_type: vm_name
        vm_username: 'root'
        vm_password: 'VMware1!'
        vm_shell: /usr/bin/rm
        vm_shell_args: -rf /home/phoenix/setting.sh
        wait_for_process: True
      delegate_to: localhost

    - name: reboot vm
      community.vmware.vmware_guest_powerstate:
        hostname: '{{ my_vcenter_hostname }}'
        username: '{{ my_vcenter_username }}'
        password: '{{ my_vcenter_password }}'
        validate_certs: 'false'
        name: "k8s-master"
        state: reboot-guest
      delegate_to: localhost
      register: deploy