# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_instant_clone_module.html#ansible-collections-community-vmware-vmware-guest-instant-clone-module

---
- hosts: localhost
  vars_files: ./vars.yml

  tasks: 
  - name: Instant Clone a VM with guest_customization
    community.vmware.vmware_guest_instant_clone:
      hostname: '{{ my_vcenter_hostname }}'
      username: '{{ my_vcenter_username }}'
      password: '{{ my_vcenter_password }}'
      validate_certs: false
      datacenter: TEST
      vm_username: "root"
      vm_password: "VMware1!"
      datastore: test-iscsi
      host: '{{ item.host }}'
      name: '{{ item.name }}'
      parent_vm: "k8s-master"
      wait_vm_tools: true
    with_items:
    - {host: "sa-esxi-04.vclass.local", name: "k8s-worker-01" }
    - {host: "sa-esxi-05.vclass.local", name: "k8s-worker-02" }
    - {host: "sa-esxi-06.vclass.local", name: "k8s-worker-03" }
    register: Instant_cloned_guest_customize
    delegate_to: localhost