# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_deploy_ovf_module.html#ansible-collections-community-vmware-vmware-deploy-ovf-module

---
- hosts: localhost
  vars_files: ./vars.yml

# Deploys a new VM named 'test_VM' in specific datacenter/cluster, with network mapping taken from variable and using ova template from an absolute path
  tasks: 
  - name: Create SiteA ESXi VMs
    community.vmware.vmware_deploy_ovf:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      datacenter: '{{datacenter_name}}'
      folder: '{{ folder_prefix + student_ID }}'
      esxi_hostname: "{{ esxi_hostname }}"
      datastore: '{{ datastore_name }}'
      name: test_vm      
      #networks: "{u'S11-SA-Mgmt':u'{{ 'S11-SA-Mgmt' }}'}"
      networks: 
        name: S11-SA-Mgmt
        type: standard
      power_on: false
      ovf: /mnt/c/test/S11-SA-ESXi-04/S11-SA-ESXi-04.ovf
      #wait_for_ip_address: true
    delegate_to: localhost

# - community.vmware.vmware_deploy_ovf:
#     hostname: '{{ vcenter_hostname }}'
#     username: '{{ vcenter_username }}'
#     password: '{{ vcenter_password }}'
#     datacenter: Datacenter1
#     esxi_hostname: test-server
#     datastore: test-datastore
#     ovf: /path/to/ubuntu-16.04-amd64.ovf
#   delegate_to: localhost