# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_deploy_ovf_module.html#ansible-collections-community-vmware-vmware-deploy-ovf-module

---
- hosts: localhost
  vars_files: ./vars.yml

# Deploys a new VM named 'test_VM' in specific datacenter/cluster, with network mapping taken from variable and using ova template from an absolute path
  tasks: 
  - name: Create SiteA ESXi VMs
    community.vmware.vmware_deploy_ovf:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      datacenter: '{{datacenter_name}}'
      folder: '{{ folder_prefix + student_ID }}'
      esxi_hostname: "{{ esxi_hostname }}"
      datastore: '{{ datastore_name }}'
      name: test_vm      
      networks: 
        '{{ 'S11-SA-Mgmt' }}':'{{ 'S11-SA-Mgmt' }}'
        '{{ 'S11-Trunk' }}':'{{ 'S11-Trunk' }}'
      power_on: false
      ovf: /mnt/c/test/S11-SA-ESXi-04/S11-SA-ESXi-04.ovf
      wait_for_ip_address: true
    delegate_to: localhost

  # - name: Configure network adapter
  #   community.vmware.vmware_guest_network:
  #     hostname: "{{ vcenter_hostname }}"
  #     username: "{{ vcenter_username }}"
  #     password: "{{ vcenter_password }}"
  #     validate_certs: False
  #     name: test_vm
  #     label: '{{ item.label }}'
  #     network_name: '{{ item.network_name }}'
  #     state: present
  #   with_items:
  #   - {label: "Network apdapter 1",network_name: "{{ student_ID + '-SA-Mgmt' }}" }
  #   - {label: "Network apdapter 2",network_name: "{{ student_ID + '-SA-Mgmt' }}" }
  #   - {label: "Network apdapter 3",network_name: "{{ student_ID + '-Trunk' }}" }
  #   - {label: "Network apdapter 4",network_name: "{{ student_ID + '-Trunk' }}" }
  #   delegate_to: localhost