## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_export_ovf_module.html#ansible-collections-community-vmware-vmware-export-ovf-module

---
- hosts: localhost
  vars_files: ./vars.yml

  tasks:
  - name : export_vm_ovf
    community.vmware.vmware_export_ovf:
      hostname: '{{ vcenter_hostname }}' 
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      name: '{{ student_ID + '-SA-ESXi-04' }}'
      export_with_images: true
      export_dir: /path/to/ovf_template/
    delegate_to: localhost