https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_host_service_manager_module.html#ansible-collections-community-vmware-vmware-host-service-manager-module
---
- hosts: localhost
  vars_files: ./vars.yml

  tasks: 
  - name: Start ntpd setting for an ESXi Host
    community.vmware.vmware_host_service_manager:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      esxi_hostname: '{{ esxi_hostname }}'
      service_name: ntpd
      state: present
    delegate_to: localhost

  # - name: Stop ntpd setting for an ESXi Host
  #   community.vmware.vmware_host_service_manager:
  #     hostname: '{{ vcenter_hostname }}'
  #     username: '{{ vcenter_username }}'
  #     password: '{{ vcenter_password }}'
  #     esxi_hostname: '{{ esxi_hostname }}'
  #     service_name: ntpd
  #     state: absent
  #   delegate_to: localhost